iOS-2 | Добавление протоколов и расширений
iOS-vk-education/2023_2_CakesHub pull request #5
Opened 2024-03-16 00:40 UTC by mightyK1ngRichard

2024-03-22 09:13 UTC, blackplayerten requested changes

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/CGFloat+Extentions.swift
> +    var toString: String { "\(self)" }
это расширение тоже убрать

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/CGSize+Extensions.swift
> +    }
убрать

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/DispatchQueue.swift
> +}
убрать

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/NSObjectProtocol+Extensions.swift
> +    @discardableResult
лучше писать по месту использования, так код будет более прозрачен 

а саму функцию with убрать

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/Optional+Extenstions.swift
> +}
убрать

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/String+Extensions.swift
> +    static let rub = "₽"
если не все знаки используются, то лишние удалить

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/View+Extentions.swift
> +extension View {
лучше делать не экстеншн от базового
а его создать
например 
```swift 
struct BasicView: View {
    var body: some View {
        HStack {
            
        }
    }
    
    func offsetX(...)
    ....
}
```

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/SwiftUI/Image+Additions.swift
> +extension Image {
не делаем экстеншены от базовых классов
заменяем на 
```swift 
struct CHImage: Image {
     static let basketIcon = Image("basketIcon")
}

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/SwiftUI/Text+Extenstions.swift
> +extension Text {
аналогично как с картинками

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/Extensions/UIKit/UIImage+Additions.swift
> +extension UIImage {
переделать

2024-03-22 09:13 UTC, blackplayerten commented on CakesHub/CakesHub/Helpers/SwiftUIPreview.swift
> +    func updateUIView(_ view: UIView, context: Context) {}
если тело пустое значит код в данный момент не нужен
убрать

2024-03-22 21:47 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/CGFloat+Extentions.swift
> +    var toString: String { "\(self)" }
Убранно

2024-03-22 21:48 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/DispatchQueue.swift
> +}
Убранно

2024-03-22 21:49 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/NSObjectProtocol+Extensions.swift
> +    @discardableResult
Убранно

2024-03-22 21:49 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/Optional+Extenstions.swift
> +}
убрано

2024-03-22 21:54 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/Foundation/CGSize+Extensions.swift
> +    }
убрано

2024-03-22 22:14 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/SwiftUI/Image+Additions.swift
> +extension Image {
Поменял

2024-03-22 22:25 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/SwiftUI/Text+Extenstions.swift
> +extension Text {
Убрал

2024-03-22 22:27 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/Extensions/UIKit/UIImage+Additions.swift
> +extension UIImage {
убрал

2024-03-22 22:28 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Helpers/SwiftUIPreview.swift
> +    func updateUIView(_ view: UIView, context: Context) {}
Его нельзя убрать, оно прям таким и должно быть

<img width="1368" alt="image" src="https://github.com/iOS-vk-education/2023_2_CakesHub/assets/90796324/b28ad162-54ff-4d44-8a2f-57e572888934">

2024-03-27 16:08 UTC, blackplayerten approved these changes

2024-03-27 16:12 UTC, closed without merging