iOS-4 | Добавление главного экрана
iOS-vk-education/2023_2_CakesHub pull request #7
Opened 2024-03-16 00:56 UTC by mightyK1ngRichard

## [Эпик задачи](https://github.com/iOS-vk-education/2023_2_CakesHub/pull/1)

Добавлен главный экран.

2024-03-17 10:48 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/MainScreen/View/MainView.swift
> +            .scrollIndicators(.hidden)
это можно написать так: ScrollView(showsIndicators: false)

2024-03-17 10:48 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/MainScreen/View/MainView.swift
> +            .background(Color.bgMainColor)
множество таких свойств (если в компоненте имеются данные) можно кофигурировать как

```swift
struct ProductsStack: View {
    var body: some View {
        VStack {
            fillContent()
        }
        .background()
        .padding(.top, 40)
    }
    
    func fillContent() -> some View {
        EmptyView()
    }
}

struct MainView: View {
    var body: some View {
         ProductsStack()
            .fillContent()
    }
}
```

2024-03-17 13:38 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/MainScreen/View/MainView.swift
> +            .scrollIndicators(.hidden)
Можно кнч, но это уже не модно

<img width="465" alt="image" src="https://github.com/iOS-vk-education/2023_2_CakesHub/assets/90796324/de621da9-a610-4c5a-ba51-e17aa59fd5ab">

2024-03-22 11:33 UTC, blackplayerten requested changes

2024-03-22 11:33 UTC, blackplayerten commented on CakesHub/CakesHub/Entities/ProductRequest/ProductRequest+Mock.swift
> +}
не пишем так

2024-03-22 11:33 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/MainScreen/ViewModel/MainViewModel.swift
> +        DispatchQueue.global().asyncAfter(deadline: .now() + 5) {
почему с задержкой? если будущая норм модель, а не мок

2024-03-22 22:31 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Entities/ProductRequest/ProductRequest+Mock.swift
> +}
Это уже убрал в главной ветке iOS-1. Видимо сюда не скопипастилось

2024-03-22 22:38 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/MainScreen/ViewModel/MainViewModel.swift
> +        DispatchQueue.global().asyncAfter(deadline: .now() + 5) {
Да, уже можно убрать. Убрал

2024-03-27 16:07 UTC, blackplayerten approved these changes

2024-03-27 16:12 UTC, closed without merging