iOS-5 | Добавлен экран информации о товаре
iOS-vk-education/2023_2_CakesHub pull request #8
Opened 2024-03-16 00:58 UTC by mightyK1ngRichard

## [Эпик задачи](https://github.com/iOS-vk-education/2023_2_CakesHub/pull/1)

Добавлен экран подробной информации о товаре и его рейтинге

2024-03-22 11:47 UTC, blackplayerten requested changes

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/Model/NewProductDetailModel+Mock.swift
> +private extension String {
не пишем

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/Model/NewProductDetailModel+Mock.swift
> +private extension [String] {
аналогично

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/Components/PickersSectionView.swift
> +    struct PickersItem: Identifiable, Hashable {
private?

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/ProductDetailScreen.swift
> +            // FIXME: iOS-17: Применить корректный паттерн роутинга
надо применить))))))))

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/ProductDetailScreen.swift
> +private extension String {
не пишем

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/ViewModel/ProductDetailViewModel.swift
> +        DispatchQueue.global().asyncAfter(deadline: .now() + 2) { [weak self] in
почему с задержкой?

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/Models/ProductReviewsModelMockData.swift
> +private extension String {
исправить

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/View/ProductReviewsScreen.swift
> +private extension String {
исправить

2024-03-22 11:47 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/View/ProductReviewsScreen.swift
> +                    }
уверена это можно в экстеншн вынести

2024-03-22 22:39 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/Model/NewProductDetailModel+Mock.swift
> +private extension String {
все эти вещи уже также в iOS-1 убрал, сюда не подлились видимо

2024-03-22 22:39 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/Model/NewProductDetailModel+Mock.swift
> +private extension [String] {
все эти вещи уже также в iOS-1 убрал, сюда не подлились видимо

2024-03-22 22:40 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/Components/PickersSectionView.swift
> +    struct PickersItem: Identifiable, Hashable {
Он снаружи принимается 

![Uploading image.png…]()

2024-03-22 22:42 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/ProductDetailScreen.swift
> +            // FIXME: iOS-17: Применить корректный паттерн роутинга
уже, опять же не подлились изменения )

2024-03-22 22:42 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/View/ProductDetailScreen.swift
> +private extension String {
Тоже убрано уже

2024-03-22 22:43 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/ProductDetailScreen/ViewModel/ProductDetailViewModel.swift
> +        DispatchQueue.global().asyncAfter(deadline: .now() + 2) { [weak self] in
Это да, просто проверял, что меняются состояния. убрал

2024-03-22 22:44 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/Models/ProductReviewsModelMockData.swift
> +private extension String {
Тоже уже исправленно

2024-03-22 22:44 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/View/ProductReviewsScreen.swift
> +private extension String {
аналогично

2024-03-22 22:51 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/ProductDetail/RatingReviewsScreen/View/ProductReviewsScreen.swift
> +                    }
Вынес

2024-03-27 16:05 UTC, blackplayerten approved these changes

2024-03-27 16:07 UTC, blackplayerten approved these changes

2024-03-27 16:12 UTC, closed without merging