iOS-6 | Добавление экрана категорий
iOS-vk-education/2023_2_CakesHub pull request #9
Opened 2024-03-16 00:59 UTC by mightyK1ngRichard

## [Эпик задачи](https://github.com/iOS-vk-education/2023_2_CakesHub/pull/1)

2024-03-22 11:49 UTC, blackplayerten requested changes

2024-03-22 11:49 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/CategoriesScreen/View/CategoriesView.swift
> +    // FIXME: Сделать по умному
забавно)

2024-03-22 11:49 UTC, blackplayerten requested changes

2024-03-22 11:49 UTC, blackplayerten commented on CakesHub/CakesHub/Streams/ProductStream/CategoriesScreen/View/CategoriesView.swift
> +                .scrollClipDisabled()
вот это наверняка можно отдельно написать

2024-03-22 23:03 UTC, mightyK1ngRichard commented on CakesHub/CakesHub/Streams/ProductStream/CategoriesScreen/View/CategoriesView.swift
> +    // FIXME: Сделать по умному
Да, тут уже попраил, марку убрал

2024-03-27 16:05 UTC, blackplayerten approved these changes

2024-03-27 16:12 UTC, closed without merging